CREATE TABLE `trace_submissions` (
	`id` text PRIMARY KEY NOT NULL,
	`submitter_email` text NOT NULL,
	`submitter_name` text,
	`trace_filename` text NOT NULL,
	`metadata_filename` text,
	`trace_storage_key` text NOT NULL,
	`metadata_storage_key` text,
	`trace_bytes` integer NOT NULL,
	`metadata_bytes` integer DEFAULT 0 NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`public_consent` integer DEFAULT false NOT NULL,
	`review_note` text,
	`reviewed_at` text,
	`reviewed_by` text,
	`run_id` text,
	`model` text,
	`model_family` text,
	`method` text,
	`gpu_type` text,
	`gpu_count` text,
	`row_count` integer NOT NULL,
	`gpu_ids_json` text NOT NULL,
	`headers_json` text NOT NULL,
	`created_at` text NOT NULL
);
